# Generated by Django 2.2.17 on 2020-12-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_finaly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finaly',
            name='title',
        ),
        migrations.AddField(
            model_name='finaly',
            name='final',
            field=models.CharField(default=1, max_length=100, verbose_name='最後の一文'),
            preserve_default=False,
        ),
    ]
