# Generated by Django 2.2.17 on 2020-12-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201221_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='topimage',
        ),
        migrations.AddField(
            model_name='profile',
            name='topimage1',
            field=models.ImageField(default=1, upload_to='images', verbose_name='トップ画像1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='topimage2',
            field=models.ImageField(default=1, upload_to='images', verbose_name='トップ画像2'),
            preserve_default=False,
        ),
    ]
