# Generated by Django 2.2.17 on 2020-12-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201223_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='character1',
            field=models.ImageField(default=1, upload_to='images', verbose_name='性格１'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='character2',
            field=models.ImageField(default=1, upload_to='images', verbose_name='性格２'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='character3',
            field=models.ImageField(default=1, upload_to='images', verbose_name='性格３'),
            preserve_default=False,
        ),
    ]
