# Generated by Django 2.2.17 on 2020-12-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201223_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=100, verbose_name='電話番号')),
                ('mail', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100, verbose_name='住所')),
                ('hour1', models.CharField(max_length=100, verbose_name='営業時間１')),
                ('hour2', models.CharField(max_length=100, verbose_name='営業時間２')),
                ('hour3', models.CharField(max_length=100, verbose_name='営業時間３')),
            ],
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
