# Generated by Django 2.2.17 on 2020-12-25 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201225_1401'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotter',
            new_name='Footer',
        ),
    ]
