# Generated by Django 2.2.17 on 2020-12-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201225_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='topimage3',
            field=models.ImageField(default=1, upload_to='images', verbose_name='トップ画像３'),
            preserve_default=False,
        ),
    ]
